server:
  port: 8005
spring:
  application:
    name: service-center
  mail:
    port: 465
    host: smtp.gmail.com
    properties:
      "mail.smtp.ssl.enable": true
  cloud:
    stream:
      bindings:
        output:
          destination: login-exchange # 表示要使用的Exchange名称定义
          content-type: application/json # 消息类型
          binder: defaultRabbit # 要绑定的消息服务的具体设置
      rabbit:
        bindings:
          output:
            producer:
              ttl: 60000 #消息几秒不消费转入私信队列
              autoBindDlq: true #启动私信队列
              deadLetterExchange: dead-letter-exchange #绑定exchange
