server:
  port: 8007
spring:
  application:
    name: service-statistic
  cloud:
    stream:
      bindings:
        StatLoginCount:
          destination: login-exchange # 表示要使用的Exchange名称定义
          content-type: application/json # 消息类型
          binder: defaultRabbit # 要绑定的消息服务的具体设置
          group: statistic
        rabbit:
          bindings:
            StatLoginCount:
              consumer:
                ttl: 60000 #消息几秒不消费转入私信队列
                autoBindDlq: true #启用死信队列，默认会生成一个DLX EXCHANGE，当消息重复消费失败后
                deadLetterExchange: dead-letter-exchange #绑定exchange
