server:
  port: 8002

aliyun:
  oss:
    file:
      endpoint: "oss-cn-beijing.aliyuncs.com"
      keyId: "LTAI5tQuSDdfWgK4PKARXAf5"
      keySecret: "CDtiUfRWo2vK5Pf6dJVqqS5T6xhr4a"
      bucketName: "my-online-education-project"

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
