server:
  port: 8001
spring:
  application:
    name: service-edu
  cloud:
    stream:
      bindings:
        buyCountCourse-in-0: # input
          destination: course-buy-count-exchange # 表示要使用的Exchange名称定义
          content-type: application/json # 消息类型
          binder: defaultRabbit # 要绑定的消息服务的具体设置
          group: course
        courseViewCountStat-out-0: # output
          destination: course-view-stat-exchange # 表示要使用的Exchange名称定义
          content-type: application/json # 消息类型
          binder: defaultRabbit # 要绑定的消息服务的具体设置
      rabbit:
        bindings:
          buyCountCourse-in-0:
            consumer:
              ttl: 60000 #消息60秒不消费转入死信队列
              autoBindDlq: true #启用死信队列，默认会生成一个DLX EXCHANGE，当消息重复消费失败后
              deadLetterExchange: dead-letter-exchange
          courseViewCountStat-out-0:
            producer:
              autoBindDlq: true #启用死信队列，默认会生成一个DLX EXCHANGE，当消息重复消费失败后
              deadLetterExchange: dead-letter-exchange
      function:
        definition: buyCountCourse
